require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccessTokensController do

  # This should return the minimal set of attributes required to create a valid
  # AccessToken. As you add validations to AccessToken, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all access_tokens as @access_tokens" do
      access_token = AccessToken.create! valid_attributes
      get :index
      assigns(:access_tokens).should eq([access_token])
    end
  end

  describe "GET show" do
    it "assigns the requested access_token as @access_token" do
      access_token = AccessToken.create! valid_attributes
      get :show, :id => access_token.id.to_s
      assigns(:access_token).should eq(access_token)
    end
  end

  describe "GET new" do
    it "assigns a new access_token as @access_token" do
      get :new
      assigns(:access_token).should be_a_new(AccessToken)
    end
  end

  describe "GET edit" do
    it "assigns the requested access_token as @access_token" do
      access_token = AccessToken.create! valid_attributes
      get :edit, :id => access_token.id.to_s
      assigns(:access_token).should eq(access_token)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AccessToken" do
        expect {
          post :create, :access_token => valid_attributes
        }.to change(AccessToken, :count).by(1)
      end

      it "assigns a newly created access_token as @access_token" do
        post :create, :access_token => valid_attributes
        assigns(:access_token).should be_a(AccessToken)
        assigns(:access_token).should be_persisted
      end

      it "redirects to the created access_token" do
        post :create, :access_token => valid_attributes
        response.should redirect_to(AccessToken.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved access_token as @access_token" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccessToken.any_instance.stub(:save).and_return(false)
        post :create, :access_token => {}
        assigns(:access_token).should be_a_new(AccessToken)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccessToken.any_instance.stub(:save).and_return(false)
        post :create, :access_token => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested access_token" do
        access_token = AccessToken.create! valid_attributes
        # Assuming there are no other access_tokens in the database, this
        # specifies that the AccessToken created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AccessToken.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => access_token.id, :access_token => {'these' => 'params'}
      end

      it "assigns the requested access_token as @access_token" do
        access_token = AccessToken.create! valid_attributes
        put :update, :id => access_token.id, :access_token => valid_attributes
        assigns(:access_token).should eq(access_token)
      end

      it "redirects to the access_token" do
        access_token = AccessToken.create! valid_attributes
        put :update, :id => access_token.id, :access_token => valid_attributes
        response.should redirect_to(access_token)
      end
    end

    describe "with invalid params" do
      it "assigns the access_token as @access_token" do
        access_token = AccessToken.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccessToken.any_instance.stub(:save).and_return(false)
        put :update, :id => access_token.id.to_s, :access_token => {}
        assigns(:access_token).should eq(access_token)
      end

      it "re-renders the 'edit' template" do
        access_token = AccessToken.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccessToken.any_instance.stub(:save).and_return(false)
        put :update, :id => access_token.id.to_s, :access_token => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested access_token" do
      access_token = AccessToken.create! valid_attributes
      expect {
        delete :destroy, :id => access_token.id.to_s
      }.to change(AccessToken, :count).by(-1)
    end

    it "redirects to the access_tokens list" do
      access_token = AccessToken.create! valid_attributes
      delete :destroy, :id => access_token.id.to_s
      response.should redirect_to(access_tokens_url)
    end
  end

end
